x-config:
  - &EXPRESS_BUILDER "expressjs-demo"
  - &CONTAINER_NAME "express-demo"

version: '3.7'

services:
  # build a node server image to run our code on (docker-compose build node)
  express:
    build:
      context: .
      dockerfile: Dockerfile
    image: *EXPRESS_BUILDER
    container_name: build_node_demo
  # mount current src files and run on node builder (docker-compose up dev)
  dev:
    image: *EXPRESS_BUILDER
    container_name: *CONTAINER_NAME
    ports:
      - '8080:8080'
    volumes:
      - ./src:/usr/src/app/src 
    command: npm run start
